name: centjes-import-revolut
version: 0.0.0.0
github: "NorfairKing/centjes"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - cassava
  - centjes
  - envparse
  - optparse-applicative
  - path
  - path-io
  - text
  - time
  - vector
  - yaml

executables:
  centjes-import-revolut:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes-import-revolut

