# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# centjes-stripe:test/Centjes/Stripe/OptParseSpec.hs:13
# To update this it, run the test with --golden-reset
{ lib }:
{
  import = lib.mkOption {
    default = { };
    type = lib.types.submodule {
      options = {
        assets-account = lib.mkOption {
          default = null;
          description = "Account name of the Stripe balance";
          type = lib.types.nullOr lib.types.str;
        };
        begin = lib.mkOption {
          default = null;
          description = "The first month to import, default: January of this year";
          type = lib.types.nullOr lib.types.str;
        };
        currency = lib.mkOption {
          default = null;
          description = "The currency Stripe settles in";
          type = lib.types.nullOr lib.types.str;
        };
        deductible-tags = lib.mkOption {
          default = null;
          description = "Tags for an expense transaction whose expenses carried recoverable VAT";
          type = lib.types.nullOr (lib.types.listOf lib.types.str);
        };
        documents = lib.mkOption {
          default = null;
          description = "Directory of the Stripe documents downloaded by hand, relative to the ledger";
          type = lib.types.nullOr lib.types.str;
        };
        domestic-income-account = lib.mkOption {
          default = null;
          description = "Account name of domestic income";
          type = lib.types.nullOr lib.types.str;
        };
        fees-account = lib.mkOption {
          default = null;
          description = "Account name of Stripe's fees";
          type = lib.types.nullOr lib.types.str;
        };
        fees-attachment = lib.mkOption {
          default = null;
          description = "formatTime pattern for Stripe's monthly tax invoice, the one document no API serves";
          type = lib.types.nullOr lib.types.str;
        };
        fees-vat-rate = lib.mkOption {
          default = null;
          description = "The percentage Stripe charges VAT on its own fees at";
          type = lib.types.nullOr lib.types.number;
        };
        foreign-income-account = lib.mkOption {
          default = null;
          description = "Account name of foreign income";
          type = lib.types.nullOr lib.types.str;
        };
        home-country = lib.mkOption {
          default = null;
          description = "The two-letter country whose VAT this ledger owes";
          type = lib.types.nullOr lib.types.str;
        };
        key = lib.mkOption {
          default = null;
          description = "Stripe API key that can read the balance and payouts and create report runs";
          type = lib.types.nullOr lib.types.str;
        };
        key-file = lib.mkOption {
          default = null;
          description = "Stripe API key that can read the balance and payouts and create report runs";
          type = lib.types.nullOr lib.types.str;
        };
        not-vat-deductible-tags = lib.mkOption {
          default = null;
          description = "Tags for an expense transaction whose expenses carried no VAT";
          type = lib.types.nullOr (lib.types.listOf lib.types.str);
        };
        opening-account = lib.mkOption {
          default = null;
          description = "Account name that the opening balance comes from";
          type = lib.types.nullOr lib.types.str;
        };
        output = lib.mkOption {
          default = null;
          description = "Output file path, which this importer rewrites";
          type = lib.types.nullOr lib.types.str;
        };
        payout-account = lib.mkOption {
          default = null;
          description = "Account name of the self-transfer that payouts go through";
          type = lib.types.nullOr lib.types.str;
        };
        refunds-account = lib.mkOption {
          default = null;
          description = "Account name of money given back to customers";
          type = lib.types.nullOr lib.types.str;
        };
        reports = lib.mkOption {
          default = null;
          description = "Directory to save the monthly report CSVs into, relative to the ledger";
          type = lib.types.nullOr lib.types.str;
        };
        vat-expenses-account = lib.mkOption {
          default = null;
          description = "Account name of the VAT paid, which is what gets reclaimed";
          type = lib.types.nullOr lib.types.str;
        };
        vat-income-account = lib.mkOption {
          default = null;
          description = "Account name of the VAT charged to customers";
          type = lib.types.nullOr lib.types.str;
        };
      };
    };
  };
  ledger = lib.mkOption {
    default = null;
    description = "ledger file";
    type = lib.types.nullOr lib.types.str;
  };
}
