- ignore:
    name: "Use ++"
- ignore:
    name: "Use &&"
- ignore:
    name: "Redundant lambda"
- ignore:
    name: "Redundant if"
- ignore:
    name: "Replace case with maybe"
- ignore:
    name: "Avoid lambda using `infix`"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use underscore"
- ignore:
    name: "Use record patterns"
- ignore:
    name: "Use tuple-section"
- ignore:
    name: "Use unless"
- ignore:
    name: "Use putStr"
# Until we can upgrade to a newer hlint:
# https://github.com/ndmitchell/hlint/issues/1557
- ignore:
    name: "Unused LANGUAGE pragma"


# Functions that we dissallow.
# Note that you _can_ add exceptions to these hints, but those exceptions should be thorougly reviewed.
- functions:
  - {name: unsafeDupablePerformIO, within: []} # Unsafe
  - {name: unsafeInterleaveIO, within: []} # Unsafe
  - {name: unsafeFixIO, within: []} # Unsafe
  - name: unsafePerformIO # Unsafe

  - {name: forkIO, within: []} # Hard to get right, use the async library instead.

  - {name: throw, within: []} # Don't throw from pure code, use throwIO instead.


  - {name: Data.List.head, within: []} # Partial
  - {name: Data.List.tail, within: []} # Partial
  - {name: Data.List.init, within: []} # Partial
  - {name: Data.List.last, within: []} # Partial
  - {name: '!!', within: []} # Partial

  - {name: until, within: []} # Really confusing, use 'when' instead.

  - name: toEnum # Partial

  - {name: Data.Foldable.foldl, within: []} # Lazy. Use foldl' instead.

  # Don't use strings to interact with files
  - {name: System.IO.readFile, within: []}
  - {name: System.IO.writeFile, within: []}
  - {name: System.IO.appendFile, within: []}

  # Don't use string for command-line output.
  - {name: System.IO.putStr, within: []}
  - {name: System.IO.print, within: []}
  - name: System.IO.putChar

  # Don't use string for command-line input either.
  - {name: System.IO.getChar, within: []}
  - {name: System.IO.getLine, within: []}
  - {name: System.IO.getContents, within: []} # Does lazy IO.
  - {name: System.IO.interact, within: []}
  - {name: System.IO.readIO, within: []}
  - {name: System.IO.readLn, within: []}

  # Can succeed in dev, but fail in prod, because of encoding guessing
  # It's also Lazy IO.
  # See https://www.snoyman.com/blog/2016/12/beware-of-readfile/ for more info.
  - {name: System.IO.readFile, within: []}
  - name: Data.Text.IO.readFile, 
    within:
    - "Centjes.FormatSpec"
    - "Centjes.ParseSpec"

  - {name: Data.Text.IO.Lazy.readFile, within: []}

  - {name: Prelude.read, within: []} # Partial, use `Text.Read.readMaybe` instead.

  - {name: nub, within: []} # O(n^2)


  - name: decodeUtf8 # Partial, use decodeUtf8' instead.
    within:
      - Centjes.Switzerland.Command.Taxes
      - Centjes.Switzerland.Command.VAT
  - name: Prelude.putStrLn
    within:
      - Centjes.Docs.Site.ModuleDocs
      - Centjes.Docs.Site.DependencyGraph
      - Centjes.Docs.Site.Handler.Reload
      - Centjes.Switzerland.Constants


  # Does unexpected things, see
  # https://github.com/NorfairKing/haskell-WAT#real-double
  - name: realToFrac
    within:
      - Centjes.Command.RatesGraph
      - Centjes.Report.Balance # TODO get rid of this by putting  positiveFraction in Money.Account
      - Centjes.Switzerland.Report.Taxes.Typst
      - Centjes.Switzerland.Report.VAT.Typst

  # Does silent truncation:
  # > fromIntegral (300 :: Word) :: Word8
  # 44
  - name: fromIntegral
    within:
      - Centjes.Compile.compileConversionRate
      - Centjes.Format
      - Centjes.Formatting.accountWidth
      - Centjes.Import.Cornercard
      - Centjes.Import.Neon
      - Centjes.Chart.Command.All
      - Centjes.Timestamp

- modules:
  - { name: Debug.Trace, within: [] }
