resolver: lts-21.22
packages:

- centjes
- centjes-gen

- centjes-import-revolut

- centjes-switzerland

- centjes-docs-site


ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
- diagnose-2.5.1@sha256:853fd268d7fe0191b79d73187104bf7b4bc5ce3bc3483cb088dc10b09f18abc8,5977

                  
- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0
                 
- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399
            
- github: NorfairKing/template-haskell-reload
  commit: c416550db3f353bad65980a8ecd9b3b81fa504bd
  subdirs:    
    - template-haskell-reload
                


- github: NorfairKing/really-safe-money
  commit: 954209a8bf1f4c9843fc789cde8cd44955ac92f1
  subdirs:
  - really-safe-money
  - really-safe-money-autodocodec
  - really-safe-money-gen

- github: NorfairKing/autodocodec
  commit: 0e48f4dd464b87471008b74fba2b997b80729fc2
  subdirs:  
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema

- github: NorfairKing/validity
  commit: 657cf4bdc2731387abea6e707b88d381d5218616
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-network-uri
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-case-insensitive
  - validity-containers
  - validity-network-uri
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

system-ghc: true
nix:
  enable: false
with-hpack: hpack
