resolver: lts-22.22
packages:

- centjes
- centjes-gen

- centjes-import-cornercard
- centjes-import-neon
- centjes-import-revolut

- centjes-switzerland

- centjes-docs-site


ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

flags:              
  zip:           
    disable-bzip2: true

extra-deps:
- diagnose-2.5.1@sha256:853fd268d7fe0191b79d73187104bf7b4bc5ce3bc3483cb088dc10b09f18abc8,5977

                  
- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0
                 
- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399
            
- github: NorfairKing/template-haskell-reload
  commit: c416550db3f353bad65980a8ecd9b3b81fa504bd
  subdirs:    
    - template-haskell-reload
                


- github: NorfairKing/really-safe-money
  commit: 11ae98bc0bfd590f3802d2bb6d94fc77ffb34515
  subdirs:
  - really-safe-money
  - really-safe-money-autodocodec
  - really-safe-money-gen
- github: NorfairKing/safe-coloured-text
  commit: 26b7657428f277f819a0831cbddddb7f4c5408f9
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/validity
  commit: 51b8843b9bd5228160b99f653d3271147245d689
  subdirs:
    - validity
    - validity-dlist
    - genvalidity
    - genvalidity-dlist
- github: NorfairKing/autodocodec
  commit: b435803c3367b06c0d38acd90a54ba63e63fb6be
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/opt-env-conf
  commit: ecfcf2a41edad94fd2b7c1d0bdd8654fbcb1545c
  subdirs:
    - opt-env-conf
    - opt-env-conf-test


system-ghc: true
nix:
  enable: false
with-hpack: hpack
