name: centjes-gen
version: 0.0.0.0
github: "NorfairKing/centjes"

extra-source-files:
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - centjes
  - containers
  - diagnose
  - genvalidity
  - genvalidity-containers
  - genvalidity-path
  - genvalidity-text
  - genvalidity-time
  - genvalidity-vector
  - monad-logger
  - path
  - really-safe-money
  - really-safe-money-gen
  - sydtest
  - text
  - vector

tests:
  centjes-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - centjes
    - centjes-gen
    - containers
    - genvalidity-containers
    - genvalidity-sydtest
    - genvalidity-text
    - monad-logger
    - mtl
    - opt-env-conf
    - path
    - path-io
    - really-safe-money
    - safe-coloured-text
    - sydtest
    - text
    - time
    - yaml
