name: centjes-gen
version: 0.0.0.0
github: "NorfairKing/centjes"

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - array
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - bytestring
  - centjes
  - containers
  - deepseq
  - diagnose
  - envparse
  - genvalidity
  - genvalidity-containers
  - genvalidity-path
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-text
  - genvalidity-time
  - genvalidity-vector
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - prettyprinter
  - prettyprinter-ansi-terminal
  - primitive
  - random
  - really-safe-money
  - really-safe-money-gen
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
  - scientific
  - sydtest
  - text
  - time
  - unliftio
  - validity
  - validity-containers
  - validity-path
  - validity-scientific
  - validity-text
  - validity-time
  - validity-vector
  - vector
  - yaml

tests:
  centjes-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - centjes
    - centjes-gen
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-path
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - genvalidity-vector
    - monad-logger
    - path
    - path-io
    - really-safe-money
    - really-safe-money-gen
    - scientific
    - sydtest
    - text
    - time
    - vector
    - centjes
