name: centjes-docs-site
version: 0.0.0
github: NorfairKing/centjes
license: MIT
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu

extra-source-files:
- routes
- content/pages/**/*
- content/unreleased.markdown
- templates/**/*
- test_resources/**/*
- options.nix
dependencies:
- base >= 4.7

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - aeson
  - blaze-html
  - bytestring
  - centjes
  - centjes-import-cornercard
  - centjes-import-neon
  - centjes-import-revolut
  - centjes-switzerland
  - cmark
  - containers
  - data-default
  - file-embed
  - filepath
  - fsnotify
  - opt-env-conf
  - path
  - path-io
  - safe-coloured-text
  - shakespeare
  - skylighting
  - template-haskell
  - template-haskell-reload
  - text
  - th-lift-instances
  - wai-extra
  - warp
  - yesod
  - yesod-autoreload
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote

executables:
  centjes-docs-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes-docs-site

tests:
  centjes-docs-site-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes-docs-site
    - sydtest
    - opt-env-conf-test
