name: centjes-docs-site
version: 0.0.0
github: NorfairKing/centjes
license: MIT
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu

extra-source-files:
- routes
- content/pages/**/*
- content/unreleased.markdown
- templates/**/*

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - base >= 4.7
  - bytestring
  - cmark-gfm
  - containers
  - data-default
  - envparse
  - file-embed
  - filepath
  - fsnotify
  - optparse-applicative
  - path
  - path-io
  - shakespeare
  - centjes
  - centjes-import-revolut
  - centjes-switzerland
  - template-haskell
  - template-haskell-reload
  - text
  - th-lift-instances
  - time
  - wai-extra
  - warp
  - yesod
  - yesod-autoreload
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote

executables:
  centjes-docs-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - centjes-docs-site
