name: centjes
version: 0.0.0.0
github: "NorfairKing/centjes"

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  build-tools:
  - alex
  - happy
  - autoexporter
  dependencies:
  - array
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - containers
  - deepseq
  - envparse
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - prettyprinter
  - random
  - really-safe-money
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
  - text
  - time
  - validity
  - validity-path
  - validity-text
  - validity-time
  - validity-vector
  - vector
  - yaml

executables:
  centjes:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes

tests:
  centjes-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - centjes
    - genvalidity
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - genvalidity-vector
    - really-safe-money-gen
    - sydtest
    - text
