name: centjes
version: 0.0.0.0
github: "NorfairKing/centjes"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools:
  - alex
  - happy
  - autoexporter
  dependencies:
  - array
  - autodocodec
  - bytestring
  - containers
  - diagnose
  - dlist
  - fast-myers-diff
  - monad-logger
  - mtl
  - opt-env-conf
  - path
  - path-io
  - prettyprinter
  - prettyprinter-ansi-terminal
  - psqueues
  - really-safe-money
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
  - text
  - time
  - unliftio
  - validity
  - validity-containers
  - validity-path
  - validity-text
  - validity-time
  - validity-vector
  - vector

executables:
  centjes:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes

