name: centjes-cryptocurrencies
version: 0.0.0.0
github: "NorfairKing/centjes"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - centjes
  - conduit
  - containers
  - http-client
  - http-client-tls
  - http-types
  - monad-logger
  - opt-env-conf
  - path
  - path-io
  - really-safe-money
  - scientific
  - text
  - time

executables:
  centjes-cryptocurrencies:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes-cryptocurrencies
