name: centjes-switzerland
version: 0.0.0.0
github: "NorfairKing/centjes"

extra-source-files:
- templates/**/*.typ
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5


library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - centjes
  - containers
  - containers
  - envparse
  - monad-logger
  - optparse-applicative
  - path
  - path-io
  - really-safe-money
  - text
  - time
  - typed-process
  - vector
  - yaml

executables:
  centjes-switzerland:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - centjes-switzerland

tests:                       
  centjes-switzerland-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:   
    - -threaded      
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - autodocodec-yaml
    - centjes
    - centjes-gen
    - centjes-switzerland
    - filepath
    - monad-logger  
    - path            
    - path-io
    - sydtest
    - sydtest-aeson
